### ISSUE TITLE
Step 4 of Readme: wrong file name: confgure_permission.py

### ISSUE THREAD

**Issue by elisboa** [Caduedu14/cerberus#3]
On step 4 of readme, it says to run this command:
`python confgure_permission.py --user {username}`
but the correct file name is configure_permissions.py, so it should be:
`python configure_permissions.py --user {username}`

**Comment by Caduedu14** [comment]
Fixed on [Docs: fix name of script and parameter](https://github.com/Caduedu14/cerberus/commit/01a89d789a26d6edfedbedd49c95eca146a97cd4)
